[pyprland]
plugins = [
  "scratchpads",
  "expose",
  "workspaces_follow_focus",
]

[workspaces_follow_focus]
max_workspaces = 9

[expose]
include_special = false

[scratchpads.emacs]
animation = "fromBottom"
command = "alacritty -e emacsclient --alternate-editor 'false' -t"
class = "Alacritty"
lazy = true
size = "75% 45%"
# unfocus = "hide"
margin = 0

[scratchpads.chromium]
animation = "fromRight"
command = "chromium"
class = "chromium-browser"
lazy = true
size = "45% 90%"
# unfocus = "hide"
margin = 0
